<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Product;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function similarProducts(Product $product)
    {
        $query = $this->createQueryBuilder('product');

        $query->join('product.categories', 'category');

        $query->where(
            $query->expr()->in('category', ':productCategories'),
            'product.id <> :id'
        );

        $query->setParameter('productCategories', $product->getCategories());
        $query->setParameter('id', $product->getId());

        return $query->getQuery()->getResult();
    }
}
