<?php

namespace AppBundle\Repository;

/**
 * SaleStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaleStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
